name: Docker build

on:
  repository_dispatch:
    types: [update-event]
  workflow_dispatch:
  push:
    branches: [ "master" ]
    paths:
     - 'setup.sh'
     - 'startup.sh'
     - 'Dockerfile'
  pull_request:
    branches: [ "master" ]
    paths:
     - 'setup.sh'
     - 'startup.sh'
     - 'Dockerfile'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Retrieve version name
        run: |
            echo "BDBVERSION=$(grep 'export BRIDGEDBVERSION' setup.sh | sed 's|export BRIDGEDBVERSION="||g' | sed 's|\"||g')" >> $GITHUB_ENV
            
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: bigcatum/bridgedb:${{ env.BDBVERSION }}

      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: bigcatum/bridgedb:latest
