name: Docker build

on:
  push:
    branches: [ "master" ]
    paths:
     - 'setup.sh'
     - 'startup.sh'
     - 'Dockerfile'
     - '.github'
  pull_request:
    branches: [ "master" ]
    paths:
     - 'setup.sh'
     - 'startup.sh'
     - 'Dockerfile'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Retrieve version name
        run: |
            echo "version_name=$(grep 'export BRIDGEDBVERSION' setup.sh | sed 's|export BRIDGEDBVERSION="||g' | sed 's|\"||g')" >> $GITHUB_ENV
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: bigcatum/bridgedb:"${{ env.version_name }}"

      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: bigcatum/bridgedb:latest
