name: Docker build

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
    paths:
     - 'setup.sh'
     - 'startup.sh'
     - 'Dockerfile'
  pull_request:
    branches: [ "master" ]
    paths:
     - 'setup.sh'
     - 'startup.sh'
     - 'Dockerfile'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Retrieve version name
        env:
            BDBVERSION: grep 'export BRIDGEDBVERSION' setup.sh | cut -d'\"') -f2
        run: |
            echo "version name is: ${{ env.BDBVERSION }}"
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: bigcatum/bridgedb:"${{ env.BDBVERSION }}"

      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: bigcatum/bridgedb:latest
