name: ci

on:
  push:
    branches: [ "master" ]
    paths:
     - 'setup.sh'
     - 'startup.sh'
     - 'Dockerfile'
  pull_request:
    branches: [ "master" ]
    paths:
     - 'setup.sh'
     - 'startup.sh'
     - 'Dockerfile'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: name/app
          tags: |
            type=raw,value={{date 'YYYYMMDD'}}
      -
        name: Build and push version
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: bigcatum/bridgedb
          labels: ${{ steps.meta.outputs.labels }}
      -
        name: Build and push latest
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: bigcatum/bridgedb
          labels: latest

